// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7rGpFAtqoAgjBZqMe9pDmROeFv64H5Q',
    appId: '1:871229108828:web:7e2517ff8bed4432b1ac99',
    messagingSenderId: '871229108828',
    projectId: 'notasprivadas-9eaa1',
    authDomain: 'notasprivadas-9eaa1.firebaseapp.com',
    storageBucket: 'notasprivadas-9eaa1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4whoJpWzzjHyPYQWNEPVy2l5BH-2UtYg',
    appId: '1:871229108828:android:c3aeb066de3a8e87b1ac99',
    messagingSenderId: '871229108828',
    projectId: 'notasprivadas-9eaa1',
    storageBucket: 'notasprivadas-9eaa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVTW0iM20bgRjOZJWi2YaQeI7iqjP6pU',
    appId: '1:871229108828:ios:fd3a1aa62509dc8bb1ac99',
    messagingSenderId: '871229108828',
    projectId: 'notasprivadas-9eaa1',
    storageBucket: 'notasprivadas-9eaa1.firebasestorage.app',
    iosBundleId: 'com.example.notasprivadas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVTW0iM20bgRjOZJWi2YaQeI7iqjP6pU',
    appId: '1:871229108828:ios:fd3a1aa62509dc8bb1ac99',
    messagingSenderId: '871229108828',
    projectId: 'notasprivadas-9eaa1',
    storageBucket: 'notasprivadas-9eaa1.firebasestorage.app',
    iosBundleId: 'com.example.notasprivadas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7rGpFAtqoAgjBZqMe9pDmROeFv64H5Q',
    appId: '1:871229108828:web:17c42344e21e1516b1ac99',
    messagingSenderId: '871229108828',
    projectId: 'notasprivadas-9eaa1',
    authDomain: 'notasprivadas-9eaa1.firebaseapp.com',
    storageBucket: 'notasprivadas-9eaa1.firebasestorage.app',
  );
}
